

services:
  frontend:
    build:
      context: ./angularApp
    ports:
      - "4200:4200"
    volumes:
      - ./angularApp:/app

  backend:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
